/*
 * SPDX-FileCopyrightText: 2023-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#define ESP_PANEL_BOARD_DEFAULT_USE_CUSTOM (1)

#if ESP_PANEL_BOARD_DEFAULT_USE_CUSTOM
#define ESP_PANEL_BOARD_NAME "Waveshare:ESP32-S3-Touch-LCD-4.3"
#define ESP_PANEL_BOARD_WIDTH (800)
#define ESP_PANEL_BOARD_HEIGHT (480)

// LCD Configuration
#define ESP_PANEL_BOARD_USE_LCD (1)
#define ESP_PANEL_BOARD_LCD_CONTROLLER ST7262
#define ESP_PANEL_BOARD_LCD_BUS_TYPE (ESP_PANEL_BUS_TYPE_RGB)

#if ESP_PANEL_BOARD_LCD_BUS_TYPE == ESP_PANEL_BUS_TYPE_RGB
#define ESP_PANEL_BOARD_LCD_RGB_CLK_HZ (16 * 1000 * 1000)
#define ESP_PANEL_BOARD_LCD_RGB_DATA_WIDTH (16)
#define ESP_PANEL_BOARD_LCD_RGB_PIXEL_BITS (ESP_PANEL_LCD_COLOR_BITS_RGB565)
#define ESP_PANEL_BOARD_LCD_RGB_BOUNCE_BUF_SIZE (ESP_PANEL_BOARD_WIDTH * 10)

// IO Pins
#define ESP_PANEL_BOARD_LCD_RGB_IO_HSYNC (46)
#define ESP_PANEL_BOARD_LCD_RGB_IO_VSYNC (3)
#define ESP_PANEL_BOARD_LCD_RGB_IO_DE (5)
#define ESP_PANEL_BOARD_LCD_RGB_IO_PCLK (7)
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA0 (14)
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA1 (38)
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA2 (18)
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA3 (17)
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA4 (10)
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA5 (39)
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA6 (0)
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA7 (45)
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA8 (48)
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA9 (47)
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA10 (21)
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA11 (1)
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA12 (2)
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA13 (42)
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA14 (41)
#define ESP_PANEL_BOARD_LCD_RGB_IO_DATA15 (40)
#endif

// Touch Configuration
#define ESP_PANEL_BOARD_USE_TOUCH (1)
#define ESP_PANEL_BOARD_TOUCH_CONTROLLER GT911
#define ESP_PANEL_BOARD_TOUCH_BUS_TYPE (ESP_PANEL_BUS_TYPE_I2C)
#define ESP_PANEL_BOARD_TOUCH_I2C_IO_SCL (9)
#define ESP_PANEL_BOARD_TOUCH_I2C_IO_SDA (8)

// Backlight and Expander
#define ESP_PANEL_BOARD_USE_BACKLIGHT (1)
#define ESP_PANEL_BOARD_BACKLIGHT_TYPE                                         \
  (ESP_PANEL_BACKLIGHT_TYPE_SWITCH_EXPANDER)
#define ESP_PANEL_BOARD_USE_EXPANDER (1)
#define ESP_PANEL_BOARD_EXPANDER_CHIP CH422G

#endif
